# Generated by Django 4.2.1 on 2023-05-18 10:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_token_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Code',
            new_name='VerificationCode',
        ),
        migrations.RenameModel(
            old_name='Token',
            new_name='VerificationToken',
        ),
    ]
